### ISSUE TITLE
Support for function/class name with suffix is number

### ISSUE THREAD

**Issue by huynhphuchuy** [ghost-language/ghost#118]
Hi, I wonder is it possible to set the function name or class name like this: funcA1, classA1?

**Comment by kaidesu** [comment]
Sorry, I decided against this to keep identifiers across Ghost straight forward. Instead, you can use something like: `funcAOne`, `classAOne`

**Comment by kaidesu** [comment]
Actually, I'll give this some more thought. Going to re-open!

**Comment by kaidesu** [comment]
Now supported in v0.23.0 (a6c7e0918516702e055b4c886ddcd0a7ba185c3e) ✌🏻
