### ISSUE TITLE
Class with constructor got issue

### ISSUE THREAD

**Issue by huynhphuchuy** [ghost-language/ghost#119]
I got error with these lines of code:

```
class Animal {
    function constructor(breed = "bear") {
        this.breed = breed
    }
    function speak() {
        print(this.breed)
    }
}

animal = Animal.new()
animal.speak()

```

The detail error is:

`
panic: interface conversion: ast.ExpressionNode is *ast.Identifier, not *ast.Number
`

**Comment by kaidesu** [comment]
Thanks for reporting!

Looks like there's a couple issues here:

1. It's expecting that the `breed` value is defined on the class object directly
2. There's an error in the error reporting that's attempting to convert the property value to a number when its not

I'll work on resolve both of these :+1:
