### ISSUE TITLE
Support for json Object

### ISSUE THREAD

**Issue by huynhphuchuy** [ghost-language/ghost#120]
Hi Kai, I saw you have done a very good job so far, it's very nice to know about this project.

I would like to to request some more features to make ghost language better. Could you support for the json Object handling such as JSON parse (JSON Unmarshall) or JSON stringify  (JSON Marshall) ?

Thank you very much!

**Comment by kaidesu** [comment]
Yup! This has been on my list for a while now :+1:

**Comment by kaidesu** [comment]
The `json` module has been added to v0.21.0, it contains both an `encode` and `decode` method.

https://www.ghostlang.org/docs/json
