### ISSUE TITLE
Remove need of quotes for key values

### ISSUE THREAD

**Issue by kaidesu** [ghost-language/ghost#121]
Currently, you must wrap key values in quotes to assign:

```typescript
player = {
  'x': 0,
  'y': 0,
  'health': 100,
}
```

Instead I'd like to be able to define key values without, as long as there is no space in the key:

```typescript
player = {
  x: 0,
  y: 0,
  health: 100,
}
```

**Comment by huynhphuchuy** [comment]
much more convenient, thank you, please keep your good work!
