### ISSUE TITLE
Cannot call functions off of a map

### ISSUE THREAD

**Issue by huynhphuchuy** [ghost-language/ghost#123]
I got an error with Map function while List function is working well

```
z = [
  "Ghost",
  57.3,
  function (x1) {
    print("X * X")
    return x * x
  }
]

zz = {
    "name": "Ghost",
    "value": 57.3,
    "handler": function(zzz) { 
        print("zzz * zzz")
        return zzz * zzz
    }
}

print(z[2](5))
print(zz.handler(6))
```

**Comment by ryangjchandler** [comment]
I don't think maps support the method call syntax right now. The only way to do this would be using the index syntax, so `zz["handler"](6)`.

**Comment by kaidesu** [comment]
In this case it's evaluated as a "method" which was missing a case for the map object :+1:
